os: Visual Studio 2015

version: 1.0.0.{build}

configuration:
- Debug
- Release

platform: Any CPU

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

install:
- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/Latest/dotnet-dev-win-x64.latest.exe'
- cmd: dotnet-dev-win-x64.latest.exe /quiet

environment:
  PATH: $(PATH);$(PROGRAMFILES)\dotnet\

build_script:
- appveyor-retry dotnet restore -v Minimal

- dotnet build src\System.AppDomain.NetCoreApp\project.json -c %CONFIGURATION%
- dotnet build examples\NetCoreApp\project.json -c %CONFIGURATION%

- dotnet pack -c Release --no-build --version-suffix %LABEL% -o .\artifacts .\src\System.AppDomain.NetCoreApp\project.json

artifacts:
- path: artifacts\**\*.*

cache:
- '%USERPROFILE%\.nuget\packages'